// const person = {
//     firstName : 'Saravanan',
//     Designation : 'Intern',
//     Company : 'Newgen'
// };

// //Accessing values
// console.log(person.firstName);

// //Object destructing
// let {firstName,Company} = person;
// console.log(firstName,Company);

// //Storing values using Alias 
// let {firstName : Fname} = person;
// console.log(Fname);

// //String destructing 
// let Pname = 'Saravanan';
// let [a,b,c,d,e,f,g,h,i] = Pname;
// console.log(a,b,c,d,e,f,g,h,i);

// //Rest in js 
// const nums=[1,2,3,4,5,6,7,8,9,10];
// let [n1,n2, ...rest] = nums;
// console.log (n1);
// console.log(n2);
// console.log(rest);

